### ISSUE TITLE
Missing/extra dash in the lemma

### ISSUE THREAD

**Issue by laklaja** [ppke-nlpg/purepos#2]
Example:

,#--\#[\_\_COMMA___]   ->   ,#-\#[\_\_COMMA__\_]
.#--\#[\_\_PERIOD___]   ->   .#-\#[\_\_PERIOD__\_]
\`\`\#--\#[\_\_OTHER___]   ->  \`\`\#-\#[\_\_OTHER___]
Delacroix-é#Delacroix#TAG -> Delacroix-é#Delacroix-#TAG

A workaround connected with the current issue is 86c6e5a8388557f69816c4200c11ee13ebf9b82b at [here](https://github.com/ppke-nlpg/purepos/commit/86c6e5a8388557f69816c4200c11ee13ebf9b82b#diff-2326d74d08dad069cbc1276e4b7dd42cR33).

To fix this issue: Do not add (or add but, do not retrive such) suffixes to the freqTable which leave hyphen/dash at the end of the lemma... (This resolves ambiguity in decoding with maximum pobability).
What will happen when nothing can be cut from the word? (No guesses?)

**Comment by morta-code** [comment]
The commit 6fce7b9 solves the problems (according to our tests). If there are use cases where the guesser is wrong, feel free to reopen it.

**Comment by laklaja** [comment]
Great. Thanks for the supporters.
