### ISSUE TITLE
Combiners does not support incremental training

### ISSUE THREAD

**Issue by dlazesz** [ppke-nlpg/purepos#5]
The computing of lambdas in combiners does not use previous lambda values for initialisation:
[LogLinearBiCombiner.java#L34](https://github.com/ppke-nlpg/purepos/blob/0eeeb223e3eb9cf63bd03cfc1e331ddc7c74fe3e/src/main/java/hu/ppke/itk/nlpg/purepos/model/internal/LogLinearBiCombiner.java#L34)
[LogLinearTriCombiner.java#L38](https://github.com/ppke-nlpg/purepos/blob/0eeeb223e3eb9cf63bd03cfc1e331ddc7c74fe3e/src/main/java/hu/ppke/itk/nlpg/purepos/model/internal/LogLinearTriCombiner.java#L38)
[LogLinearMLCombiner.java#L18](https://github.com/ppke-nlpg/purepos/blob/0eeeb223e3eb9cf63bd03cfc1e331ddc7c74fe3e/src/main/java/hu/ppke/itk/nlpg/purepos/model/internal/LogLinearMLCombiner.java#L18)

**Comment by morta-code** [comment]
See: beb2b08
